version: '3.8'

services:
  api:
    build: .
    container_name: satcom-api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GCP_CREDENTIALS=${GCP_CREDENTIALS}
    restart: unless-stopped
    volumes:
      - ./audio:/app/audio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

